<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="11" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="5285" started-at="2017-05-24T06:30:14Z" finished-at="2017-05-24T06:30:19Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="149" started-at="2017-05-24T06:30:14Z" finished-at="2017-05-24T06:30:14Z">
      <class name="testng.ITestListener.TestListenerExample">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="beforeTest" is-config="true" duration-ms="19" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="t1()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t1" duration-ms="17" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="FAIL" signature="t2()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t2" duration-ms="1" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestListenerExample.t2()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756] should have thrown an exception of type class java.lang.RuntimeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestListenerExample.t2()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756] should have thrown an exception of type class java.lang.RuntimeException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method status="FAIL" signature="t3(java.lang.String)[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t3" duration-ms="0" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot inject @Test annotated Method [t3] with [class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [t3] with [class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:244)
	at org.testng.internal.Parameters.createParameters(Parameters.java:172)
	at org.testng.internal.Parameters.createParameters(Parameters.java:458)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:568)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method status="SUCCESS_PERCENTAGE_FAILURE" signature="t4()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t4" duration-ms="5" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at testng.ITestListener.TestListenerExample.t4(TestListenerExample.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="FAIL" signature="t4()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t4" duration-ms="3" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at testng.ITestListener.TestListenerExample.t4(TestListenerExample.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t4" duration-ms="2" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t4" duration-ms="16" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="t4" duration-ms="5" started-at="2017-05-24T14:30:14Z" finished-at="2017-05-24T14:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
      </class> <!-- testng.ITestListener.TestListenerExample -->
    </test> <!-- test1 -->
    <test name="test2" duration-ms="20" started-at="2017-05-24T06:30:19Z" finished-at="2017-05-24T06:30:19Z">
      <class name="testng.IReporter.ReporterListenerExample">
        <test-method status="PASS" signature="testAssert1(int)[pri:0, instance:testng.IReporter.ReporterListenerExample@cc285f4]" name="testAssert1" duration-ms="1" started-at="2017-05-24T14:30:19Z" data-provider="dataProvider" finished-at="2017-05-24T14:30:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert1 -->
        <test-method status="PASS" signature="testAssert1(int)[pri:0, instance:testng.IReporter.ReporterListenerExample@cc285f4]" name="testAssert1" duration-ms="2" started-at="2017-05-24T14:30:19Z" data-provider="dataProvider" finished-at="2017-05-24T14:30:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert1 -->
        <test-method status="PASS" signature="testAssert2()[pri:0, instance:testng.IReporter.ReporterListenerExample@cc285f4]" name="testAssert2" duration-ms="3" started-at="2017-05-24T14:30:19Z" finished-at="2017-05-24T14:30:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert2 -->
        <test-method status="FAIL" signature="testAssert3(int)[pri:0, instance:testng.IReporter.ReporterListenerExample@cc285f4]" name="testAssert3" duration-ms="0" started-at="2017-05-24T14:30:19Z" finished-at="2017-05-24T14:30:19Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot inject @Test annotated Method [testAssert3] with [int].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [testAssert3] with [int].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:244)
	at org.testng.internal.Parameters.createParameters(Parameters.java:172)
	at org.testng.internal.Parameters.createParameters(Parameters.java:458)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:568)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert3 -->
      </class> <!-- testng.IReporter.ReporterListenerExample -->
      <class name="testng.ITestListener.TestListenerExample">
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testng.ITestListener.TestListenerExample@9629756]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-05-24T14:30:24Z" finished-at="2017-05-24T14:30:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testng.ITestListener.TestListenerExample -->
    </test> <!-- test2 -->
  </suite> <!-- Suite1 -->
</testng-results>
